apiVersion: apps/v1
kind: Deployment
metadata:
  name: deploy-frontend
  labels: 
    app: rigup_app
    type: frontend
  namespace: yosafat-project
spec:
  replicas: 2
  selector:
    matchLabels:
      app: rigup_app
  template:
    metadata:
      name: deploy-frontend
      labels: 
        app: rigup_app
        type: frontend
    spec:
      containers:
        - name: rigup-frontend
          image: yosafatdeny/rigup_frontend:tagVersion
          ports: 
            - containerPort: 80

# ---

# apiVersion: v1
# kind: Service
# metadata:
#   name: rigup-app-service
# spec:
#   type: LoadBalancer
#   selector:
#     name: rigup-app
#   ports:
#     - port: 80
#       targetPort: 80
    
    